<a href="https://colab.research.google.com/github/saikhairnar20023/Data--science-programs/blob/main/Log_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [105]:
import pandas as pd
import numpy as np


In [106]:
df = pd.read_csv("/content/Social_Network_Ads.csv")

In [107]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [114]:
x = df.iloc[:,2:4].values
y = df.iloc[:,4].values

In [109]:
x

array([[    19],
       [ 19000],
       [    35],
       [ 20000],
       [    26],
       [ 43000],
       [    27],
       [ 57000],
       [    19],
       [ 76000],
       [    27],
       [ 58000],
       [    27],
       [ 84000],
       [    32],
       [150000],
       [    25],
       [ 33000],
       [    35],
       [ 65000],
       [    26],
       [ 80000],
       [    26],
       [ 52000],
       [    20],
       [ 86000],
       [    32],
       [ 18000],
       [    18],
       [ 82000],
       [    29],
       [ 80000],
       [    47],
       [ 25000],
       [    45],
       [ 26000],
       [    46],
       [ 28000],
       [    48],
       [ 29000],
       [    45],
       [ 22000],
       [    47],
       [ 49000],
       [    48],
       [ 41000],
       [    45],
       [ 22000],
       [    46],
       [ 23000],
       [    47],
       [ 20000],
       [    49],
       [ 28000],
       [    47],
       [ 30000],
       [    29],
       [ 43000],
       [    31

In [115]:
from sklearn.model_selection import train_test_split

In [116]:
x_train, x_test, y_train, y_test  =  train_test_split(x,y, test_size=0.2,random_state =0)

In [117]:
x_test

array([[    30,  87000],
       [    38,  50000],
       [    35,  75000],
       [    30,  79000],
       [    35,  50000],
       [    27,  20000],
       [    31,  15000],
       [    36, 144000],
       [    18,  68000],
       [    47,  43000],
       [    30,  49000],
       [    28,  55000],
       [    37,  55000],
       [    39,  77000],
       [    20,  86000],
       [    32, 117000],
       [    37,  77000],
       [    19,  85000],
       [    55, 130000],
       [    35,  22000],
       [    35,  47000],
       [    47, 144000],
       [    41,  51000],
       [    47, 105000],
       [    23,  28000],
       [    49, 141000],
       [    28,  87000],
       [    29,  80000],
       [    37,  62000],
       [    32,  86000],
       [    21,  88000],
       [    37,  79000],
       [    57,  60000],
       [    37,  53000],
       [    24,  58000],
       [    18,  52000],
       [    22,  81000],
       [    34,  43000],
       [    31,  34000],
       [    49,  36000],


In [118]:
from sklearn.preprocessing import StandardScaler

In [119]:
sc = StandardScaler()

In [121]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [129]:
x_test

array([[-0.49618606,  0.56021375],
       [ 0.2389044 , -0.59133674],
       [-0.03675452,  0.18673792],
       [-0.49618606,  0.31122986],
       [-0.03675452, -0.59133674],
       [-0.77184498, -1.52502632],
       [-0.40429975, -1.68064126],
       [ 0.05513178,  2.33422397],
       [-1.59882175, -0.03112299],
       [ 1.06588117, -0.80919764],
       [-0.49618606, -0.62245972],
       [-0.67995868, -0.43572181],
       [ 0.14701809, -0.43572181],
       [ 0.33079071,  0.24898389],
       [-1.41504914,  0.52909077],
       [-0.31241345,  1.49390334],
       [ 0.14701809,  0.24898389],
       [-1.50693545,  0.49796778],
       [ 1.80097163,  1.89850216],
       [-0.03675452, -1.46278035],
       [-0.03675452, -0.6847057 ],
       [ 1.06588117,  2.33422397],
       [ 0.51456332, -0.56021375],
       [ 1.06588117,  1.1204275 ],
       [-1.13939022, -1.27604243],
       [ 1.24965379,  2.24085501],
       [-0.67995868,  0.56021375],
       [-0.58807237,  0.34235285],
       [ 0.14701809,

In [122]:
from sklearn.linear_model import LogisticRegression

In [123]:
Log = LogisticRegression()

In [124]:
Log.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [125]:
pred_y =Log.predict(x_test)

In [126]:
pred_y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [132]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [130]:
accuracy_score(y_test , pred_y)

0.8875

In [133]:
confusion_matrix(y_test,pred_y)

array([[52,  6],
       [ 3, 19]])