<a href="https://colab.research.google.com/github/saikhairnar20023/Data--science-programs/blob/main/program_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

functions with parameters :

In [ ]:
def greet_user(name): #Parameter
  print(f"Hi", name)
  print("WELCOME ABROAD")

In [ ]:
greet_user("sai") #Arguments

Hi sai
WELCOME ABROAD


In [ ]:
def greet_user(first ,last): #Parameter
  print(f"Hi {first}  {last} ")
  print("WELCOME TO JAPAN")

In [ ]:
greet_user("Sai" ,"Khairnar")

Hi Sai  Khairnar 
WELCOME TO JAPAN


In [ ]:
greet_user(last = "khairnar", first = "Sai")

Hi Sai  khairnar 
WELCOME TO JAPAN


In [ ]:
import math

In [ ]:
math.factorial(5)

120

In [ ]:
import time

In [31]:
for i in range(10):
  print(i)
  time.sleep(1)

0
1
2
3
4
5
6
7
8
9


In [32]:
import random

In [33]:
random.randint()

4

In [38]:
import numpy as np

In [37]:
a = [1,2,3,4]
b = [5,6,7,8]

In [39]:
c = np.array([1,2,3,4])
d = np.array([5,6,7,8])

In [40]:
c

array([1, 2, 3, 4])

In [41]:
d

array([5, 6, 7, 8])

In [42]:
c * d

array([ 5, 12, 21, 32])